on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  check-conventional-commits:
    uses: armakuni/github-actions/.github/workflows/check-conventional-commits.yml@v0.19.4

  generate-terraform-docs:
    if: github.ref == 'refs/heads/main'
    uses: armakuni/github-actions/.github/workflows/generate-terraform-docs.yml@v0.19.4
    with:
      output-file: README.md
      # This artifact is referenced by the cog.toml
      artifact-name: terraform-docs

  create-release:
    needs:
    - check-conventional-commits
    - generate-terraform-docs
    if: github.ref == 'refs/heads/main'
    uses: armakuni/github-actions/.github/workflows/tag-and-release.yml@v0.19.4
    secrets: inherit
    with:
      download-artifacts: true
